### ISSUE TITLE
retry on 5xx

### ISSUE THREAD

**Issue by netlob** [statsfm/spotify.js#39]

**Comment by netlob** [comment]
<img width="1160" alt="image" src="https://user-images.githubusercontent.com/33723199/154824631-8fd5aeef-04a5-4a12-9982-39dde8f23b3e.png">

**Comment by netlob** [comment]
@stingalleman any updates on this?

**Comment by Syjalo** [comment]
How about make Request Manager? Manager may handle 4xx, 5xx and prevent rate limits.
