### ISSUE TITLE
rewrite axios handler

### ISSUE THREAD

**Issue by stingalleman** [statsfm/spotify.js#45]
The current HTTP manager file is a mess and there are possible issues with it - it would be better to rewrite it and maybe ditch Axios for a better alternative.

**Comment by joeydotdev** [comment]
What kind of issues have you ran into in the past with the current implementation?

**Comment by stingalleman** [comment]
@joeydotdev It's a mess, not well-tested and probably has a lot of bugs. There's also a small chance that there might be a memory leak in there - although I'm not sure, I haven't been able to reproduce it.

**Comment by joeydotdev** [comment]
> @joeydotdev It's a mess, not well-tested and probably has a lot of bugs. There's also a small chance that there might be a memory leak in there - although I'm not sure, I haven't been able to reproduce it.

Gotcha. Using this library for something I'm working on - so don't mind helping out / being listening ears for what direction you want to take the library in
